return {'My grandfather used to tell me of how grand Aredia City was.',
	'He once mentioned a royal Pok[e\']mon that brought the kings great joy and prosperity.',
	'This Pok[e\']mon was said to live in the old Aredia Castle with the king.',
	'Its powers sustained life and happiness in all the land.',
	'Then a wicked king rose to power and locked the Pok[e\']mon away in a room of treasures.',
	'With the Pok[e\']mon locked away, the people in Aredia became sad and the castle began to crumble.',
	'Since then, the castle has been abandoned and we are no longer led by kings.',
	'Prince Ryan goes down to the old castle occasionally to pay his respects to his ancestors, but assures us that there is no ancient Pok[e\']mon there.',
	'I guess my story is not entirely true, after all.',
	'Imagine that, though, a Pok[e\']mon locked away in a room in those ruins all this time.'}