return {'Hey there.',
	'How have you kids been?',
	'How is Tess?',
	'Is she being safe?',
	'Oh I know I worry too much, but I feel so responsible for her.',
	'When she was young, her parents left her here with me and told me they were just going on a little adventure together.',
	'They said nothing else about it.',
	'They never did return though, and nobody has heard or seen from them since then.',
	'I think she\'s eager to explore and search for her lost parents, but it\'s no use.',
	'The rest of the family has been looking for them for years.',
	'Just make sure she stays safe for me, please.'}