return {'We\'ve just recently discovered that there are tunnels beneath Brimber City formed by flowing lava.',
	'Right now, we\'re unsure of how to access these tunnels.',
	'They\'re filled with a poisonous smog generated by the volcano.'}